### PR TITLE
Try rebase format

### PR DESCRIPTION
**Pull request by yhmtsai**

### CODE REVIEW

**Comment by yhmtsai** [comment]
rebase-format!

**Comment by upsj** [comment]
Error: The following files need to be formatted:
```
include/ginkgo/core/matrix/coo.hpp
include/ginkgo/core/matrix/csr.hpp
```
You can find a formatting patch under **Artifacts** [here](https://github.com/upsj/ginkgo-bot-playground/actions/runs/1367764224) or run `format!` if you have write access to Ginkgo

**Comment by yhmtsai** [comment]
format-rebase!

**Comment by upsj** [comment]
Formatting rebase introduced changes, see Artifacts [here](https://github.com/upsj/ginkgo-bot-playground/actions/runs/1367769970) to review them

**Comment by upsj** [comment]
Error: The following files need to be formatted:
```
include/ginkgo/core/matrix/coo.hpp
include/ginkgo/core/matrix/csr.hpp
```
You can find a formatting patch under **Artifacts** [here](https://github.com/upsj/ginkgo-bot-playground/actions/runs/1367775132) or run `format!` if you have write access to Ginkgo

**Comment by yhmtsai** [comment]
format-rebase!

**Comment by upsj** [comment]
Formatting rebase introduced changes, see Artifacts [here](https://github.com/upsj/ginkgo-bot-playground/actions/runs/1367780663) to review them

**Comment by upsj** [comment]
Error: Cannot push rebased branch, are edits for maintainers allowed?

**Comment by upsj** [comment]
Error: The following files need to be formatted:
```
include/ginkgo/core/matrix/coo.hpp
include/ginkgo/core/matrix/csr.hpp
```
You can find a formatting patch under **Artifacts** [here](https://github.com/upsj/ginkgo-bot-playground/actions/runs/1367781974) or run `format!` if you have write access to Ginkgo

**Pull request closed without merging**
